name: Deploy ADF Pipelines

on:
  push:
    branches:
      - souvikTestADF  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - souvikTestADF  # Trigger the workflow on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: '2.30.0'  # Correct input for specifying Azure CLI version
        inlineScript: |
          az --version  # Example inline script to verify Azure CLI setup

    - name: Install jq
      run: sudo apt-get install jq

    - name: Login to Azure
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}  # Make sure to store your Azure credentials as secrets

    - name: Read pipeline JSON files and deploy
      run: |
        # Ensure the correct path to the JSON files
        linkedService1=$(cat ./linkedService/TestLinkedService.json)
        
        # Construct a JSON array with the pipeline contents
        linkedServices=$(jq -n \
          --arg linkedService1 "$linkedService1" \
          '[
            {
              "name": "TestLinkedService",
              "definition": $linkedService1 | fromjson
            }
          ]')

        # Deploy using Bicep (or ARM template)
        az deployment group create \
          --resource-group "komatsu" \
          --template-file ./bicep/modules/linkedservice.bicep \
          --parameters dataFactoryName=ADF033 \
          --parameters linkedServices="$linkedServices"
