name: Deploy ADF Pipelines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: '2.30.0'

    - name: Install jq
      run: sudo apt-get install jq

    - name: Login to Azure
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

    - name: Read pipeline JSON files and deploy
      run: |
        linkedService1=$(cat ./linkedService/TestLinkedService.json)

        linkedServices=$(jq -n \
          --arg linkedService1 "$linkedService1" \
          '[
            {
              "name": "TestLinkedService",
              "definition": $linkedService1 | fromjson
            }
          ]')

        az deployment group create \
          --resource-group "komatsu" \
          --template-file ./bicep/main.bicep \
          --parameters dataFactoryName=ADF033 \
          --parameters linkedServices="$linkedServices"
